In [2]:
import pandas as pd

In [ ]:
df_sujo = pd.read_csv("C:\\saas1\\despesas-domesticas\\data\\despesas_familia_suja.csv")
df_sujo

,id,data,descricao,estabelecimento,categoria,subcategoria,valor,forma_pagamento,tipo_despesa,essencial,responsavel
0,1228,2026-04-17,Combustível,Posto Shell,Transporte,Combustível,187.06,Cartão de crédito,Variável,Sim,Pai
1,275,06/05/2024,Academia,SmartFit,Saúde,Academia,119.90,Cartão de crédito,Fixa,Não,Mãe
2,52,2023-11-12,Pizza,Sushi Kai,Alimentação,Restaurantes e delivery,"R$ 183,94",Cartão de crédito,Variável,N,Mãe
3,118,05/01/2024,Aluguel,Imobiliária Central,Moradia,Aluguel,2200.00,Boleto,Fixa,sim,Casal
4,716,21-03-25,Compras de supermercado,Atacadão,Alimentacao,Supermercado,143.30,Cartão de débito,Variável,Sim,Casal
...,...,...,...,...,...,...,...,...,...,...,...
1452,987,2025-10-25,Compras de supermercado,Mercado do Bairro,Alimentação,Supermercado,96.97,Cartão de crédito,Variável,S,Casal
1453,134,2024-01-18,Feira / hortifrúti,Feira Livre,Alimentação,Hortifruti,"R$ 131,15",Pix,Variável,Sim,Mãe
1454,362,2024-07-10,Plano de saúde família,Unimed,Saúde,Plano de saúde,1450.00,boleto,Fixa,Sim,Casal
1455,1365,2026-08-05,Padaria,Padaria Pão Quente,Alimentação,Padaria,58.80,Cartão de débito,Variável,S,Mãe
1456,452,2024-09-18,Conta de água,Companhia de Saneamento,Moradia,Água,112.33,Débito automático,Variável,Sim,Casal

In [4]:
df_sujo.info()

<class 'pandas.DataFrame'>
RangeIndex: 1457 entries, 0 to 1456
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1457 non-null   int64
 1   data             1454 non-null   str
 2   descricao        1457 non-null   str
 3   estabelecimento  1457 non-null   str
 4   categoria        1457 non-null   str
 5   subcategoria     1457 non-null   str
 6   valor            1453 non-null   str
 7   forma_pagamento  1432 non-null   str
 8   tipo_despesa     1457 non-null   str
 9   essencial        1457 non-null   str
 10  responsavel      1437 non-null   str
dtypes: int64(1), str(10)
memory usage: 263.0 KB

In [5]:
df_sujo.shape

(1457, 11)

In [6]:
df_sujo["categoria"].unique()

<ArrowStringArray>
[       'Transporte',             'Saúde',       'Alimentação',
           'Moradia',       'Alimentacao',       'alimentação',
       'ALIMENTAÇÃO',             'lazer',          'Educação',
         ' Moradia ',          'Educacao',           'VIAGENS',
       'Comunicação',             'Lazer',     ' Comunicação ',
 'Cuidados pessoais',        'TRANSPORTE',           'moradia',
         'Vestuário',              'Pets',        'transporte',
        ' Educação ',           'Compras',      ' Transporte ',
       'Comunicacao',             'saúde',           'Viagens',
         'Presentes',           ' Saúde ', 'CUIDADOS PESSOAIS',
         ' Viagens ',     ' Alimentação ',             'LAZER',
           ' Lazer ',           'MORADIA',          'educação',
         'vestuário',       'comunicação',              'pets',
             'SAÚDE',         'VESTUÁRIO',             'Saude',
       'COMUNICAÇÃO',              'PETS',           'compras',
          'EDUCAÇÃO',         'presentes']
Length: 47, dtype: str

In [7]:
df_sujo.isna().sum()

id                  0
data                3
descricao           0
estabelecimento     0
categoria           0
subcategoria        0
valor               4
forma_pagamento    25
tipo_despesa        0
essencial           0
responsavel        20
dtype: int64

In [8]:
df_sujo["essencial"].unique()

<ArrowStringArray>
['Sim', 'Não', 'N', 'sim', 'S', 'não', 'nao']
Length: 7, dtype: str

In [9]:
df_sujo["forma_pagamento"].unique()

<ArrowStringArray>
['Cartão de crédito',            'Boleto',  'Cartão de débito',
               'Pix', 'cartão de crédito', 'Cartao de credito',
 'Débito automático',               'PIX',               'pix',
                 nan,            'boleto',  'Cartao de debito',
 'CARTÃO DE CRÉDITO',  'CARTÃO DE DÉBITO',  'cartão de débito',
            'BOLETO', 'débito automático', 'Debito automatico',
 'DÉBITO AUTOMÁTICO']
Length: 19, dtype: str

In [10]:
df_sujo["responsavel"].unique()

<ArrowStringArray>
[    'Pai',     'Mãe',   'Casal',       nan, 'Filho 1',     'pai', 'Filho 2',
   'casal',     'mãe',  'Filho2',     'Mae', 'filho 1', 'filho 2',  'Filho1']
Length: 14, dtype: str

In [11]:
df_sujo.duplicated().sum()

np.int64(18)

In [12]:
df_sujo_copy = df_sujo.copy()

In [13]:
df_sujo.duplicated().sum()

np.int64(18)

In [14]:
df_sujo_copy.drop_duplicates(inplace=True)

In [15]:
df_sujo_copy.shape

(1439, 11)

In [16]:
def limpa_valor(x):
    if pd.isna(x):
        return 0
    x = str(x).replace("R$", "").strip()
    if "," in x:
        x = x.replace(".", "").replace(",", ".")
    return float(x)

In [17]:
df_sujo_copy["valor"] = df_sujo_copy["valor"].apply(limpa_valor)
df_sujo_copy["valor"].dtype

dtype('float64')

In [18]:
df_sujo_copy["valor"].isna().sum()

np.int64(0)

In [19]:
df_sujo_copy["valor"].describe()

count    1.439000e+03
mean     6.702367e+03
std      1.642834e+05
min      0.000000e+00
25%      7.037000e+01
50%      1.516500e+02
75%      2.850000e+02
max      5.679200e+06
Name: valor, dtype: float64

In [20]:
df_sujo_copy.sort_values("valor", ascending=False).head(6)[["id", "descricao", "categoria", "valor"]]

       id                      descricao    categoria       valor
878   967                     Condomínio      Moradia  5679200.00
338   334                    Combustível   Transporte  2254700.00
339   825             Feira / hortifrúti  Alimentação  1239900.00
672   860  Viagem de férias (hospedagem)      Viagens     4458.83
872   376  Viagem de férias (hospedagem)      Viagens     4159.67
1068  933                 Geladeira nova      Compras     3290.00

In [21]:
df_sujo["data"].sample(10)

1399    2026-09-18
1225    2026-02-01
1152    2025-08-18
786     15/10/2024
19      2024-05-02
1339    2025-03-25
547     2025-05-26
612     2024-05-05
83      2024-01-08
385     2024-05-21
Name: data, dtype: str

In [22]:
df_sujo_copy["subcategoria"].unique()

<ArrowStringArray>
[                   'Combustível',                       'Academia',
        'Restaurantes e delivery',                        'Aluguel',
                   'Supermercado',                        'Padaria',
                            'Gás',                     'Condomínio',
             'Consultas e exames',                     'Aplicativo',
                 'Entretenimento',                    'Combustivel',
                     'APLICATIVO',                       ' Cursos ',
                        'ENERGIA',            'Mensalidade escolar',
                         'Cursos',           'Transporte da viagem',
                       'Internet',                  ' Combustível ',
                   'SUPERMERCADO',        'RESTAURANTES E DELIVERY',
                        'Energia',                    'ASSINATURAS',
                    'Assinaturas',                        'Celular',
                     'Hortifruti',               'Higiene e beleza',
                 'Plano de saúde',                   'supermercado',
                       'Farmácia',              'Roupas e calçados',
                          'Ração',                           'Água',
                    'Seguro auto',                       'INTERNET',
                'Datas especiais',                     'HORTIFRUTI',
 'Eletrônicos e eletrodomésticos',                    'Veterinario',
                   'Aniversários',            'Serviços domésticos',
                          'Natal',            'Manutenção do carro',
                    'assinaturas',                      ' Padaria ',
                        'PADARIA',                           'IPVA',
                   ' Aplicativo ',                 ' Supermercado ',
                        'ALUGUEL',                     ' Farmácia ',
                    'combustível',                        'celular',
                       'Passeios',                          'Racao',
            'Servicos domesticos',               'higiene e beleza',
                           'Agua',                    'Veterinário',
                     'aplicativo',              'roupas e calçados',
             'Manutenção da casa',                       'academia',
                     'CONDOMÍNIO',                       'FARMÁCIA',
             ' Higiene e beleza ',                           'ÁGUA',
                        'padaria',                     'Hospedagem',
                           'água',                   'ANIVERSÁRIOS',
                 'PLANO DE SAÚDE',                        'aluguel',
               'HIGIENE E BELEZA',                  ' Seguro auto ',
        'restaurantes e delivery',                    'SEGURO AUTO',
                   ' Condomínio ',                   'aniversários',
                  'Licenciamento',            'MENSALIDADE ESCOLAR',
               'Material escolar',               'MATERIAL ESCOLAR',
                  ' Assinaturas ',                        'CELULAR',
            'mensalidade escolar',          ' Serviços domésticos ',
                        'energia',                    'COMBUSTÍVEL',
             'manutenção da casa']
Length: 91, dtype: str

In [23]:
import unicodedata

In [24]:
def sem_acento(s):
    return "".join(c for c in unicodedata.normalize("NFD", s)
                   if unicodedata.category(c) != "Mn")

def chave(s):
    if pd.isna(s):
        return s
    return sem_acento(s).lower().replace(" ", "")

In [25]:
categorias_validas = ["Alimentação", "Comunicação", "Compras", "Cuidados pessoais",
           "Educação", "Lazer", "Moradia", "Pets", "Presentes",
           "Saúde", "Transporte", "Vestuário", "Viagens"]

In [26]:
mapa_cat = {chave(c): c for c in categorias_validas}

df_sujo_copy["categoria"] = df_sujo_copy["categoria"].apply(chave).map(mapa_cat)